{
    "users": [
        {
            "id": 12000039962,
            "display_name": "Rosie Figliomeni",
            "email": "rosie@financethat.ca",
            "is_active": true,
            "work_number": "1-844-354-5454 ",
            "mobile_number": "647-647-9519",
        },
        {
            "id": 12000042444,
            "display_name": "Rakesh Kubersingh",
            "email": "rakesh.kubersingh@freshworks.com",
            "is_active": true,
            "work_number": null,
            "mobile_number": null,
        },
    ],
    "contacts": [
        {
            "partial": true,
            "id": 12010442668,
            "first_name": "Diane ",
            "last_name": "Diquee",
            "display_name": "Diane  Diquee",
            "avatar": null,
            "email": "heyyouchick123@gmail.com",
            "lead_score": 37,
            "last_contacted_sales_activity_mode": "SMS Outgoing",
            "job_title": null,
            "last_contacted": "2022-12-15T15:33:49-05:00",
            "last_contacted_mode": "Email Outgoing",
            "last_contacted_via_sales_activity": "2022-12-15T15:33:49-05:00",
            "work_number": "17783232914",
            "mobile_number": "17783232914",
            "sales_account_id": null,
            "record_type_id": "113000001453",
            "sales_accounts": [],
            "phone_numbers": [],
            "owner_id": 12000039962,
        }
    ],
    "sales_accounts": [],
    "deal_pipelines": [
        {
            "partial": true,
            "id": 12000025537,
            "name": "Recreation \u0026 Automotive Pipeline Public",
            "position": 1,
            "is_default": true,
            "rotting_days": 30,
            "configs": [
                {"field_name": "amount", "position": 1, "highlight": true},
                {"field_name": "sales_account_id", "position": 2, "highlight": false},
                {"field_name": "expected_close", "position": 3, "highlight": false},
            ],
            "aggregated_field": "expected_deal_value",
        }
    ],
    "deal_stages": [
        {
            "partial": true,
            "id": 12000180033,
            "name": "New",
            "position": 1,
            "forecast_type": "Open",
            "updated_at": "2022-11-11T09:31:52-05:00",
            "deal_pipeline_id": 12000025537,
            "choice_type": 5,
            "probability": 50,
        }
    ],
    "deal_types": [],
    "territories": [
        {
            "partial": true,
            "id": 12000002295,
            "name": "POWERSPORTS / CONSTRUCTION",
            "position": 1,
        }
    ],
    "currencies": [
        {
            "partial": false,
            "id": 12000024582,
            "is_active": true,
            "currency_code": "CAD",
            "exchange_rate": "1.0",
            "currency_type": 1,
            "schedule_info": null,
            "rate_change_ids": [],
        }
    ],
    "rate_changes": [],
    "lead_sources": [
        {"partial": true, "id": 12000341928, "name": "Web", "position": 1}
    ],
    "deal_reasons": [],
    "campaigns": [],
    "deal_products": [],
    "deal_payment_statuses": [],
    "deal": {
        "id": 12005307874,
        "name": "DIANE DIQUEE",
        "amount": "20000.0",
        "base_currency_amount": "20000.0",
        "expected_close": null,
        "closed_date": null,
        "stage_updated_time": "2022-09-24T17:46:49-04:00",
        "custom_field": {
            "cf_flagged": false,
            "cf_flagged_date": null,
            "cf_flagged_reason": null,
            "cf_flagged_type": null,
            "cf_reassigned": false,
            "cf_reassigned_from": null,
            "cf_deal_compliance_passed_management_only": null,
            "cf_failed_reason": null,
            "cf_lender": "Lendcare Capital",
            "cf_lc_rates": null,
            "cf_prefera_rates": null,
            "cf_dealertrack_deal_": 34826524,
            "cf_sale_type": null,
            "cf_finance_that_stock_number": null,
            "cf_credit_rating": null,
            "cf_asset_type_migrated": "Motorhome",
            "cf_asset_subtype": null,
            "cf_mobile_number": null,
            "cf_down_payment": null,
            "cf_trade_in": null,
            "cf_todays_date": "2022-12-16T00:02:09-05:00",
            "cf_status": null,
            "cf_document_sent_date": null,
            "cf_document_download_link": null,
            "cf_purchase_order_sent": false,
            "cf_purchase_order_signed": false,
            "cf_finance_that_stock_id": null,
            "cf_vehicle_year": null,
            "cf_vehicle_make": null,
            "cf_vehicle_model": null,
            "cf_vehicle_trim": null,
            "cf_vehicle_vin_": null,
            "cf_vehicle_purchase_price_": null,
            "cf_odometers_reading": null,
            "cf_vehicle_type": null,
            "cf_2_vehicle_year": 0,
            "cf_2_vehicle_make": "N/A",
            "cf_2_vehicle_model": "N/A",
            "cf_2_vehicle_trim": "N/A",
            "cf_2_vehicle_vin_hin_or_serial_number": "N/A",
            "cf_purchase_price_": 0,
            "cf_odometer_reading": null,
            "cf_payment_method": null,
            "cf_po_date": null,
            "cf_deposit": 0,
            "cf_1_total_purchase_price_": null,
            "cf_po_subtotal_": null,
            "cf_vehicle_purchase_tax_rate": 0,
            "cf_tax_total": null,
            "cf_non_taxable_items": 0,
            "cf_total_price_": null,
            "cf_fi_products": false,
            "cf_life_insurance": null,
            "cf_accident__disability": null,
            "cf_tire__rim": null,
            "cf_gap_insurance": null,
            "cf_extended_warranty": null,
            "cf_key_fob": null,
            "cf_products_total_": null,
            "cf_request_purchase_order": false,
            "cf_private_seller_name__tel": null,
            "cf_private_seller_postal_code": null,
            "cf_private_seller__province": null,
            "cf_private_seller_city": null,
            "cf_private_seller_address": null,
            "cf_email": null,
            "cf_private_seller_number": null,
            "cf_lien_paid_by": null,
            "cf_lien_amount": null,
            "cf_special_comments": null,
            "cf_best_time_to_contact": null,
            "cf_finance_that_dealer_inventory_page": null,
            "cf_purchasing_a_massimo_60_snow_blower": null,
            "cf_interested_in_financing": null,
            "cf_customer_requested_year_make__model": null,
            "cf_year_make_model": null,
            "cf_request_vin": false,
            "cf_request_color": false,
            "cf_color": null,
            "cf_available_vin": null,
            "cf_available_colors": null,
            "cf_if_you_are_selling_accessories_did_you_outline_them_properly_within_the_deal": false,
            "cf_did_you_complete_the_year_make_or_model": false,
            "cf_request_bill_of_sale": false,
            "cf_did_the_back_office_team_provide_you_with_a_vin": false,
            "cf_bill_of_sale_full_amount": false,
            "cf_massimo_60_snow_blower_attachment": false,
            "cf_snow_blower_price": null,
            "cf_60_snow_plow": false,
            "cf_60_snow_plow_price": null,
            "cf_72_snow_plow": false,
            "cf_72_snow_plow_price": null,
            "cf_heater": false,
            "cf_heater_price": null,
            "cf_utv_enclosure": false,
            "cf_utv_enclosure_price": null,
            "cf_radio": false,
            "cf_radio_price": null,
            "cf_atv_outdoor_cover": false,
            "cf_atv_cover_price": null,
            "cf_utv_outdoor_cover": false,
            "cf_utv_cover_price": null,
            "cf_request_shipping_quote": false,
            "cf_shipping_address_if_different_from_buyers_address": null,
            "cf_shipping_quote_not_including_taxes": null,
            "cf_request_delivery": false,
            "cf_inventory_location": null,
            "cf_floor_plan_company": null,
            "cf_comments": null,
            "cf_vin_check_completed": false,
            "cf_bill_of_sale_uploaded": false,
            "cf_deposit_request_sent": false,
            "cf_vehicle_price": null,
            "cf_freight__pdi": null,
            "cf_shipping_fee": null,
            "cf_installation": null,
            "cf_delivery": null,
            "cf_subtotal": null,
            "cf_deposit_amount": null,
            "cf_quote_subtotal": null,
            "cf_tax_rate": null,
            "cf_total_amount": null,
            "cf_manager": null,
            "cf_automotive_manager_commission": null,
            "cf_agent_commission": null,
            "cf_omvic_fee": null,
            "cf_licensing_fee": null,
            "cf_delivery_fee": null,
            "cf_gps": null,
            "cf_territory_rep_commission": null,
            "cf_dealer_admin_fee": null,
            "cf_dealer_reserve": null,
            "cf_warranty__insurance_amount": null,
            "cf_warranty_cost_": null,
            "cf_dealer_reserve_paid": 0,
            "cf_automotive_total_income": null,
            "cf_insurance__warranty": null,
            "cf_1_vehicle_type": null,
        },
        "probability": 50,
        "updated_at": "2022-10-06T16:05:13-04:00",
        "created_at": "2022-09-24T17:46:49-04:00",
        "deal_pipeline_id": 12000025537,
        "deal_stage_id": 12000180033,
        "age": 83,
        "links": {
            "conversations": "/crm/sales/deals/12005307874/conversations/all?include=email_conversation_recipients%2Ctargetable%2Cphone_number%2Cphone_caller%2Cnote%2Cuser\u0026per_page=3",
            "document_associations": "/crm/sales/deals/12005307874/document_associations",
            "notes": "/crm/sales/deals/12005307874/notes?include=creater",
            "tasks": "/crm/sales/deals/12005307874/tasks?include=creater,owner,updater,targetable,users,task_type",
            "appointments": "/crm/sales/deals/12005307874/appointments?include=creater,owner,updater,targetable,appointment_attendees,conference,note",
        },
        "recent_note": null,
        "completed_sales_sequences": null,
        "active_sales_sequences": null,
        "web_form_id": null,
        "upcoming_activities_time": null,
        "collaboration": {},
        "last_assigned_at": "2022-09-24T17:46:50-04:00",
        "tags": [],
        "last_contacted_sales_activity_mode": null,
        "last_contacted_via_sales_activity": null,
        "expected_deal_value": "10000.0",
        "is_deleted": false,
        "team_user_ids": null,
        "avatar": null,
        "fc_widget_collaboration": {
            "convo_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJDb252b0lkIjoiMTIwMDUzMDc4NzQiLCJ0eXBlIjoiZGVhbCJ9.IQZ897oiodtxe-gJBrbfG3kBMkSg2VKfyup4bwmpxKM",
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVc2VyVVVJRCI6IjI5MDE0MzY1MDcxNTY1MDg4NSJ9.dzh2x3T-qdVYOPpde35kz6I4cGhniAce_rfWZAVA9HM",
            "encoded_jwt_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm9kdWN0IjoiZnJlc2hzYWxlcyIsImNvbnRleHRfaWQiOiIxMjAwNTMwNzg3NCIsImNvbnRleHRfdHlwZSI6IkRlYWwiLCJwcm9kdWN0X2FjY291bnRfaWQiOiI2Mjc2MDMiLCJwcm9kdWN0X2FjY291bnRfZG9tYWluIjoiZmluYW5jZXRoYXQtY2xvbmUtNzQuZnJlc2hzYWxlcy5pbyIsInVzZXJfZW1haWwiOiJkYW5pZWxAZmluYW5jZXRoYXQuY2EiLCJpc19zZXJ2ZXIiOnRydWUsImV4cCI6MTY3MTE3NTc1OH0.0LxeCvkbwbNmW2eHfa_yZFemmmUxdvd3gm6hf6Nt8oo",
        },
        "forecast_category": null,
        "deal_prediction": 0,
        "deal_prediction_last_updated_at": null,
        "record_type_id": "113000001454",
        "freddy_forecast_metrics": null,
        "last_deal_prediction": null,
        "rotten_days": 53,
        "owner_id": 12000039962,
        "creater_id": 12000039962,
        "updater_id": 12000042444,
        "contact_ids": [12010442668],
        "sales_account_id": null,
        "deal_type_id": null,
        "territory_id": 12000002295,
        "currency_id": 12000024582,
        "lead_source_id": 12000341928,
        "deal_reason_id": null,
        "campaign_id": null,
        "deal_product_id": null,
        "deal_payment_status_id": null,
        "lookup_information": {},
    },
    "meta": null,
}
